services:

  # Apps

  migrations:
    build:
      args:
        DOTNET_ASPNET_IMAGE: mcr.microsoft.com/dotnet/aspnet:8.0
        DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
    ports:
      - 8081:8081
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8081
      
      ConnectionStrings__DefaultConnection: Host=reminders-postgres;Database=Reminders;Username=root;Password=h9pJwUUV0y;Pooling=true;
      DatabaseProvider: Postgres
      
      MigrationRunner__MaxRetryAttempts: 5
      MigrationRunner__RetryBaseDelaySeconds: 2

  dotnet-api: 
    build: 
      args: &dotnet-args
        NUGET_SOURCE: ${NUGET_SOURCE}
        NUGET_USER_NAME: ${NUGET_USER_NAME}
        NUGET_PASSWORD: ${PERSONAL_ACCESS_TOKEN}

        DOTNET_ASPNET_IMAGE: mcr.microsoft.com/dotnet/aspnet:8.0
        DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
    ports:
      - 5000:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1GB'
    depends_on:
      postgres:
        condition: service_healthy
      ganache:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CorsOrigins: http://reminders-react:3000,http://localhost:3000
      
      ConnectionStrings__DefaultConnection: Host=reminders-postgres;Database=Reminders;Username=root;Password=h9pJwUUV0y;Pooling=true;
      DatabaseProvider: Postgres

      Blockchain__PrivateKey: 0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
      Blockchain__NodeUrl: http://reminders-blockchain:8545
      Blockchain__ContractAddress: 0xf204a4Ef082f5c04bB89F7D5E6568B796096735a
    volumes: &dotnet-volumes
      - user_secrets:/root/.microsoft/usersecrets:ro
      - https_certificates:/root/.aspnet/https:ro
      - data_protection_keys:/root/.aspnet/DataProtection-Keys

  go-api:
    build: 
      args: 
        GO_IMAGE: golang:alpine
    ports:
      - 5001:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1GB'
    environment:
      PostgresDefaultConnection: postgresql://root:h9pJwUUV0y@reminders-postgres/Reminders?sslmode=disable

      CorsOrigins: http://reminders-react:3000,http://localhost:3000

  cpp-api:
    ports:
      - 5002:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1GB'
    environment:
      PostgresDefaultConnection: postgresql://root:h9pJwUUV0y@reminders-postgres/Reminders?sslmode=disable

      CorsOrigins: http://reminders-react:3000,http://localhost:3000

  mvc:
    build: 
      args: *dotnet-args
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      
      ApiOptions__BaseUrl: http://reminders-nginx:9999
      ApiOptions__HealthUrl: /health
    ports:
      - 5050:8080
    volumes: *dotnet-volumes

  react:
    build:
      args:
        NODE_IMAGE: node:18-alpine
        NEXT_PUBLIC_API_BASE_URL: http://localhost:9999
    ports:
      - '3000:3000'

  # Database

  mssql:
    environment:
      SA_PASSWORD: h9pJwUUV0y
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'
  
  postgres:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: h9pJwUUV0y
      POSTGRES_DB: Reminders
    ports:
      - 5432:5432

  # Load Balancer

  nginx: 
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"

volumes:

  user_secrets:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.microsoft/usersecrets
      o: bind

  https_certificates:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.aspnet/https
      o: bind
  
  data_protection_keys:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.aspnet/DataProtection-Keys
      o: bind

  postgres_data: